workflows:
  ios-simulator:
    name: iOS Simulator Build
    environment:
      xcode: latest
      node: 18.0.0
      cocoapods: default
    
    scripts:
      - name: Check project structure
        script: |
          echo "=== Project Structure ==="
          ls -la
          echo ""
          echo "=== iOS Directory ==="
          ls -la ios/
          echo ""
          echo "=== Flutter? ==="
          if [ -f "pubspec.yaml" ]; then
            echo "Flutter project detected"
            cat pubspec.yaml | head -10
          fi
      
      - name: Clean and setup
        script: |
          # Очистка предыдущих сборок
          cd ios
          rm -rf build Pods Podfile.lock
          pod install --repo-update --verbose
          cd ..
      
      - name: Build with detailed logs
        script: |
          cd ios
          
          # Сборка с подробным выводом ошибок
          xcodebuild build \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -destination "generic/platform=iOS Simulator" \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES \
            -verbose 2>&1 | tee build_log.txt
          
          # Проверка кода ошибки
          if [ $? -ne 0 ]; then
            echo "❌ Build failed. Showing errors:"
            grep -i error build_log.txt | head -20
            grep -A 5 -B 5 "error:" build_log.txt | head -30
            exit 1
          fi
