workflows:
  ios-debug:
    name: iOS Simple Build
    environment:
      flutter: "3.19.0"
    scripts:
      - name: Setup dependencies
        script: |
          flutter pub get
          cd ios && pod install --repo-update && cd ..

      - name: Build for simulator
        script: |
          flutter build ios --simulator --no-codesign

      - name: Verify build
        script: |
          if [ -d "build/ios/iphonesimulator/Runner.app" ]; then
            echo "✅ Build successful!"
          else
            echo "❌ Build failed"
            exit 1
          fi

    artifacts:
      - build/ios/iphonesimulator/**/*.app
