workflows:
  ios-debug:
    name: iOS Debug Build
    environment:
      xcode: latest
      flutter: stable
      cocoapods: default
    
    scripts:
      - name: Clean and setup
        script: |
          echo "=== Cleaning ==="
          rm -rf /tmp/flutter_*
          rm -rf /var/folders/*/T/flutter_tools.*
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/Runner.xcworkspace
          flutter pub get
          
      - name: Install pods
        script: |
          cd ios
          pod install --repo-update --verbose
          cd ..
          
      - name: Build iOS
        script: |
          set -e
          mkdir -p logs
          
          # Пытаемся собрать
          if flutter build ios --simulator --no-codesign --verbose 2>&1 | tee logs/build.log; then
            echo "✅ Build successful!"
          else
            echo "❌ Build failed"
            exit 1
          fi
          
      - name: Package artifacts
        script: |
          echo "=== Packaging artifacts ==="
          mkdir -p artifact_bundle
          
          # Копируем собранное приложение
          if find build/ios -name "*.app" | grep -q .; then
            mkdir -p artifact_bundle/app
            find build/ios -name "*.app" -exec cp -r {} artifact_bundle/app/ \;
          else
            echo "⚠️  No .app files found"
          fi
          
          # Копируем логи
          if [ -d "logs" ]; then
            cp -r logs/ artifact_bundle/
          fi
          
          # Создаем архив
          cd artifact_bundle
          zip -r ../taxisat_artifacts.zip . || true
          cd ..
          
          # Гарантируем что архив существует
          if [ ! -f "taxisat_artifacts.zip" ]; then
            echo "Creating empty artifact archive"
            touch empty.txt
            zip taxisat_artifacts.zip empty.txt
          fi
    
    artifacts:
      - taxisat_artifacts.zip
