workflows:
  ios-simulator:
    name: iOS Simulator Build
    environment:
      xcode: latest
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    
    scripts:
      - name: Build app
        script: |
          xcodebuild build \
            -workspace "ios/$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -destination "generic/platform=iOS Simulator" \
            CODE_SIGNING_ALLOWED=NO
