workflows:
  ios-debug:
    name: iOS Build
    environment:
      flutter: "3.32.0"
      xcode: "15.4"  # Явно указываем версию Xcode
    scripts:
      - name: Setup environment
        script: |
          echo "Flutter version:"
          flutter --version
          echo "Xcode version:"
          xcodebuild -version
          
      - name: Create Generated.xcconfig
        script: |
          mkdir -p ios/Flutter
          cat > ios/Flutter/Generated.xcconfig << 'EOL'
FLUTTER_ROOT=$FLUTTER_ROOT
FLUTTER_APPLICATION_PATH=$CM_BUILD_DIR
FLUTTER_TARGET=lib/main.dart
FLUTTER_BUILD_DIR=build
FLUTTER_BUILD_NAME=1.0.0
FLUTTER_BUILD_NUMBER=1
APPLICATION_PATH=.
EOL

      - name: Get dependencies
        script: |
          flutter pub get

      - name: Install pods with clean install
        script: |
          cd ios
          pod deintegrate
          pod install --repo-update --clean-install
          cd ..

      - name: Build with detailed logging
        script: |
          # Очищаем предыдущие сборки
          flutter clean
          
          # Собираем с подробным логированием
          flutter build ios --simulator --no-codesign --verbose 2>&1 | tee build_log.txt
          
          # Если сборка не удалась, показываем логи
          if [ ! -d "build/ios/iphonesimulator/Runner.app" ]; then
            echo "❌ Build failed, showing logs:"
            tail -100 build_log.txt
            exit 1
          fi

      - name: Verify build
        script: |
          if [ -d "build/ios/iphonesimulator/Runner.app" ]; then
            echo "✅ Build successful!"
            du -sh build/ios/iphonesimulator/Runner.app
          else
            echo "❌ Build failed"
            exit 1
          fi

    artifacts:
      - build/ios/iphonesimulator/**/*.app
      - build_log.txt
