workflows:
  ios-simulator:
    name: iOS Simulator Build
    environment:
      instance:
        xcode: latest
      vars:
        XCODE_WORKSPACE: "Rider.xcworkspace"
        XCODE_SCHEME: "Rider"
    
    scripts:
      - name: Find available simulator
        script: |
          # Получаем первый доступный iPhone симулятор
          AVAILABLE_DEVICE=$(xcrun simctl list devices | grep -E "iPhone.*Booted" | head -1 | cut -d '(' -f 1 | xargs)
          if [ -z "$AVAILABLE_DEVICE" ]; then
            AVAILABLE_DEVICE=$(xcrun simctl list devices | grep -E "iPhone" | head -1 | cut -d '(' -f 1 | xargs)
          fi
          echo "Using device: '$AVAILABLE_DEVICE'"
          
          xcodebuild build \
            -workspace "ios/$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -destination "platform=iOS Simulator,name=$AVAILABLE_DEVICE" \
            CODE_SIGNING_ALLOWED=NO
