workflows:
  ios-app-store:
    name: iOS App Store Build
    environment:
      xcode: latest
      flutter: stable
      node: 18.0.0
    
    # Переменные окружения (добавить в настройках CI)
      vars:
        APP_STORE_CONNECT_TEAM_ID: $APP_STORE_CONNECT_TEAM_ID
        APP_STORE_CONNECT_KEY_ID: $APP_STORE_CONNECT_KEY_ID
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
        BUNDLE_IDENTIFIER: com.satka.taxi.rider
        APP_STORE_APPLE_ID: $APP_STORE_APPLE_ID
    
    scripts:
      - name: Environment setup
        script: |
          echo "=== Setting up App Store environment ==="
          flutter --version
          xcodebuild -version
          
      - name: Clean and prepare
        script: |
          echo "=== Cleaning workspace ==="
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/Runner.xcworkspace
          flutter pub get
          
      - name: iOS dependencies
        script: |
          echo "=== Installing iOS dependencies ==="
          cd ios
          pod install --repo-update
          cd ..
          
      - name: Configure code signing
        script: |
          echo "=== Configuring code signing ==="
          
          # Создаем папку для профилей
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          
          # Автоматическая подпись через App Store Connect API
          if [ -n "$APP_STORE_CONNECT_PRIVATE_KEY" ]; then
            echo "Using App Store Connect API for code signing"
            
            # Создаем файл приватного ключа
            echo "$APP_STORE_CONNECT_PRIVATE_KEY" > ~/private_key.p8
            
            # Создаем ключ в keychain
            security import ~/private_key.p8 -k ~/Library/Keychains/login.keychain -T /usr/bin/codesign
            
            # Настраиваем автоматическую подпись в Xcode
            /usr/libexec/PlistBuddy -c "Set :method app-store" ios/ExportOptions.plist 2>/dev/null || \
            echo '<?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
                <key>method</key>
                <string>app-store</string>
                <key>teamID</key>
                <string>'"$APP_STORE_CONNECT_TEAM_ID"'</string>
                <key>uploadBitcode</key>
                <false/>
                <key>uploadSymbols</key>
                <true/>
            </dict>
            </plist>' > ios/ExportOptions.plist
          fi
          
      - name: Build iOS app
        script: |
          echo "=== Building iOS app ==="
          flutter build ios --release \
            --dart-define=APP_STORE=true \
            --dart-define=ENV=production
          
      - name: Create IPA archive
        script: |
          echo "=== Creating IPA archive ==="
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            archive
          
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ios/ipa \
            -allowProvisioningUpdates
    
    artifacts:
      - build/ios/ipa/Runner.ipa
