scripts:
  - name: Build with Firebase
    script: |
      # Пытаемся собрать с Firebase
      if flutter build ios --simulator --no-codesign; then
        echo "✅ Firebase build successful"
        mkdir -p build/with_firebase
        cp -r build/ios/iphonesimulator/*.app build/with_firebase/
      else
        echo "⚠️  Firebase build failed"
        # Продолжаем сборку
      fi
    
  - name: Build without Firebase
    script: |
      # Удаляем Firebase и собираем
      flutter pub remove firebase_core firebase_messaging firebase_analytics firebase_crashlytics 2>/dev/null || true
      flutter clean
      flutter pub get
      
      cd ios
      pod install
      cd ..
      
      if flutter build ios --simulator --no-codesign; then
        echo "✅ Build successful without Firebase"
        mkdir -p build/without_firebase
        cp -r build/ios/iphonesimulator/*.app build/without_firebase/
      else
        echo "❌ Build failed completely"
        exit 1
      fi
    
    artifacts:
      - build/with_firebase/*.app
      - build/without_firebase/*.app
