workflows:
  flutter-ios-workflow:
    name: Flutter iOS Build
    environment:
      groups:
        - app_credentials # Группа для сертификатов и профилей
        - firebase_vars # Добавьте эту группу для Firebase переменных
      vars:
        BUNDLE_ID: "com.satka.taxi.rider" # Ваш bundle id
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_VERSION: "3.22.0" # Укажите вашу версию Flutter

    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true

    scripts:
      - name: Set up Flutter
        script: |
          flutter --version
          flutter pub get

      - name: Set Firebase app ID
        script: |
          mkdir -p ios
          echo '{"app_id": "$FIREBASE_APP_ID"}' > ios/firebase_app_id_file.json
          echo "Firebase config file created:"
          cat ios/firebase_app_id_file.json

      - name: Build iOS
        script: |
          flutter build ipa --release --no-codesign

      - name: Code signing
        script: |
          # Создание директории для экспорта
          mkdir -p build/ios/ipa
          # Копирование .ipa файла
          cp build/ios/ipa/*.ipa build/ios/ipa/app.ipa

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
