workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    environment:
      flutter: "3.19.0"
    scripts:
      - name: Build for iOS simulator
        script: |
          flutter build ios --simulator --no-codesign
    artifacts:
      - build/ios/iphonesimulator/Runner.app
