workflows:
  ios-debug:
    name: iOS Debug Build
    max_build_duration: 60
    environment:
      groups:
        - app_store_credentials # Для сертификатов (опционально)
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.yourcompany.yourapp" # Замените на ваш
        FLUTTER_VERSION: "3.19.0"
    scripts:
      - name: Set up Flutter
        script: |
          flutter config --no-analytics
          flutter doctor -v
      - name: Get packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          cd ios && pod install && cd ..
      - name: Build iOS
        script: |
          flutter build ios --simulator --no-codesign --verbose
    artifacts:
      - build/ios/iphonesimulator/**/*.app
      - build/ios/iphonesimulator/**/*.app.dSYM
    publishing:
      email:
        recipients:
          - your-email@example.com
