workflows:
  ios-debug:
    name: iOS Debug Build
    environment:
      xcode: latest
      flutter: stable
    
    scripts:
      - name: Get full error details
        script: |
          flutter clean
          flutter pub get
          flutter build ios --simulator --no-codesign --verbose 2>&1 | tee error_log.txt
          
          # Сохраняем логи
          mkdir -p error_logs
          cp error_log.txt error_logs/
          
          # Всегда выходим с ошибкой чтобы увидеть логи
          exit 1
    
    artifacts:
      - error_logs/error_log.txt
