workflows:
  ios-debug:
    name: iOS Build
    environment:
      flutter: "3.32.0"
      xcode: "15.4"
    scripts:
      - name: Setup environment
        script: |
          echo "Flutter version:"
          flutter --version
          echo "Xcode version:"
          xcodebuild -version
          
      - name: Create Generated.xcconfig
        script: |
          mkdir -p ios/Flutter
          echo "FLUTTER_ROOT=/Users/builder/programs/flutter" > ios/Flutter/Generated.xcconfig
          echo "FLUTTER_APPLICATION_PATH=/Users/builder/clone" >> ios/Flutter/Generated.xcconfig
          echo "FLUTTER_TARGET=lib/main.dart" >> ios/Flutter/Generated.xcconfig
          echo "FLUTTER_BUILD_DIR=build" >> ios/Flutter/Generated.xcconfig
          echo "FLUTTER_BUILD_NAME=1.0.0" >> ios/Flutter/Generated.xcconfig
          echo "FLUTTER_BUILD_NUMBER=1" >> ios/Flutter/Generated.xcconfig

      - name: Update Firebase pods
        script: |
          cd ios
          # Обновляем Firebase до совместимой версии
          pod update FirebaseCoreInternal FirebaseCore
          pod install --repo-update
          cd ..

      - name: Build
        script: |
          flutter build ios --simulator --no-codesign --verbose

    artifacts:
      - build/ios/iphonesimulator/**/*.app
