workflows:
  ios-release: 
    name: iOS release
    environment:
      xcode: latest
      flutter: stable
      node: 18.0.0
    
    scripts:
      - name: Environment setup check
        script: |
          echo "=== Checking Environment ==="
          flutter --version
          xcodebuild -version
          pod --version || echo "CocoaPods not available"
          node --version
          
      - name: Enhanced clean
        script: |
          echo "=== Enhanced Cleaning ==="
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/Runner.xcworkspace
          rm -rf ~/Library/Developer/Xcode/DerivedData
          pod cache clean --all || true
          flutter pub get
      
      - name: Install flutterfire CLI
        script: |
          echo "Installing flutterfire CLI..."
          dart pub global activate flutterfire_cli
          export PATH="$PATH:$HOME/.pub-cache/bin"
          flutterfire --version || echo "Flutterfire not available"
          
      - name: iOS dependencies setup
        script: |
          echo "=== Setting up iOS dependencies ==="
          cd ios
          pod install --repo-update || pod install
          cd ..
          
      
          
          # Сборка с подробным логированием
          flutter build ios --simulator --no-codesign --verbose 2>&1 | tee error_log.txt
          
          mkdir -p error_logs
          cp error_log.txt error_logs/
          
          # Дополнительная диагностика при неудаче
          if [ -d "build/ios/iphonesimulator/Runner.app" ]; then
            echo "✅ Build successful!"
            echo "App size: $(du -sh build/ios/iphonesimulator/Runner.app)"
            exit 0
          else
            echo "❌ Build failed"
            echo "=== Error analysis ==="
            grep -i "error:" error_log.txt | head -10 || echo "No explicit errors found in log"
            grep -i "failed" error_log.txt | head -5 || true
            echo "=== Last lines of log ==="
            tail -20 error_log.txt
            exit 1
          fi
    
    artifacts:
      - build/ios/iphonesimulator/*.app
      - error_logs/
      - ios/Podfile.backup
