workflows:
  ios-simulator:
    name: iOS Simulator Build
    environment:
      xcode: latest
      flutter: stable
    
    scripts:
      - name: Flutter clean build
        script: |
          # Полная перегенерация проекта
          flutter clean
          flutter pub get
          
          # Сборка через flutter command
          flutter build ios --simulator --no-codesign --verbose --debug
      
      - name: Locate built app
        script: |
          # Ищем собранное приложение
          APP_PATH=$(find . -name "Runner.app" -type d | head -n 1)
          if [ -n "$APP_PATH" ]; then
            echo "✅ App found at: $APP_PATH"
            mkdir -p artifacts
            cp -R "$APP_PATH" artifacts/
          else
            echo "❌ App not found"
            find . -name "*.app" -type d
            exit 1
          fi
    
    artifacts:
      - artifacts/Runner.app
