workflows:
  ios-debug:
    name: iOS Simple Build
    environment:
      flutter: "3.22.0"  # Используем совместимую версию
    scripts:
      - name: Check Flutter version
        script: |
          flutter --version
          echo "CM_BUILD_DIR: $CM_BUILD_DIR"
          
      - name: Setup dependencies with retry
        script: |
          # Очищаем предыдущие сборки
          flutter clean
          rm -rf ios/Pods
          rm -f ios/Podfile.lock
          
          # Получаем зависимости Flutter
          echo "Running flutter pub get..."
          flutter pub get
          
          # Проверяем наличие Generated.xcconfig
          echo "Checking for Generated.xcconfig..."
          if [ -f "ios/Flutter/Generated.xcconfig" ]; then
            echo "✅ Generated.xcconfig exists"
            cat ios/Flutter/Generated.xcconfig
          else
            echo "❌ Generated.xcconfig missing, trying to generate..."
            # Принудительно генерируем файлы Flutter
            flutter precache
            flutter pub get
          fi
          
          # Устанавливаем pods только если конфиг существует
          if [ -f "ios/Flutter/Generated.xcconfig" ]; then
            echo "Installing pods..."
            cd ios && pod install --repo-update && cd ..
          else
            echo "Cannot install pods - Generated.xcconfig still missing"
            exit 1
          fi

      - name: Build for simulator
        script: |
          flutter build ios --simulator --no-codesign --verbose

      - name: Verify build
        script: |
          if [ -d "build/ios/iphonesimulator/Runner.app" ]; then
            echo "✅ Build successful!"
            ls -la build/ios/iphonesimulator/
          else
            echo "❌ Build failed"
            echo "Contents of build directory:"
            ls -la build/ || true
            echo "Contents of ios/Flutter directory:"
            ls -la ios/Flutter/ || true
            exit 1
          fi

    artifacts:
      - build/ios/iphonesimulator/**/*.app
