workflows:
  ios-debug:
    name: iOS Build Skip Pods
    environment:
      flutter: "3.32.0"
    scripts:
      - name: Setup without pods
        script: |
          mkdir -p ios/Flutter
          echo "FLUTTER_ROOT=/Users/builder/programs/flutter" > ios/Flutter/Generated.xcconfig
          echo "FLUTTER_APPLICATION_PATH=/Users/builder/clone" >> ios/Flutter/Generated.xcconfig
          
      - name: Build without pod install
        script: |
          # Пропускаем pod install и собираем напрямую
          flutter build ios --simulator --no-codesign --no-pod-install
