workflows:
  ios-debug:
    name: iOS Debug Build
    environment:
      xcode: latest
      flutter: stable
      node: 18.0.0  # Нужен для flutterfire
    
    scripts:
      - name: Install flutterfire CLI
        script: |
          echo "Installing flutterfire CLI..."
          dart pub global activate flutterfire_cli
          export PATH="$PATH:$HOME/.pub-cache/bin"
          flutterfire --version
          
      - name: Setup project
        script: |
          flutter clean
          flutter pub get
          
      - name: Build with disabled firebase scripts
        script: |
          # Временно отключаем скрипты Firebase
          cd ios
          if [ -f "Podfile" ]; then
            # Комментируем проблемные скрипты
            sed -i '' 's/^ *flutterfire/# flutterfire/g' Podfile 2>/dev/null || true
          fi
          cd ..
          
          flutter build ios --simulator --no-codesign --verbose 2>&1 | tee error_log.txt
          
          mkdir -p error_logs
          cp error_log.txt error_logs/
          exit 1
    
    artifacts:
      - error_logs/error_log.txt
