workflows:
  ios-simulator:
    name: iOS Simulator Build
    environment:
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Complete pod reinstallation
        script: |
          echo "=== Current directory ==="
          ls -la
          
          cd ios
          echo "=== iOS directory before ==="
          ls -la
          
          # Полная очистка
          rm -rf Pods Podfile.lock Target\ Support\ Files Runner.xcworkspace
          pod cache clean --all
          
          # Принудительная установка
          pod install --clean-install --repo-update --verbose
          
          echo "=== iOS directory after pod install ==="
          ls -la
          echo "=== Target Support Files ==="
          ls -la Target\ Support\ Files/ 2>/dev/null || echo "Not created yet"
          
          cd ..
      
      - name: Build application
        script: |
          cd ios
          xcodebuild build \
            -project Runner.xcodeproj \
            -scheme Runner \
            -sdk iphonesimulator \
            -destination "generic/platform=iOS Simulator" \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES
