workflows:
  ios-simulator:
    name: iOS Simulator Build
    environment:
      xcode: latest
    
    scripts:
      - name: Force workspace creation
        script: |
          cd ios
          
          # Удаляем старые файлы
          rm -rf Pods Podfile.lock Runner.xcworkspace
          
          # Принудительно создаем workspace
          pod install --clean-install --repo-update
          
          # Проверяем создание
          if [ ! -d "Runner.xcworkspace" ]; then
            echo "❌ Workspace still not created"
            echo "Creating manually..."
            mkdir -p Runner.xcworkspace
          fi
          
          cd ..
      
      - name: Build with project file
        script: |
          cd ios
          xcodebuild build \
            -project Runner.xcodeproj \
            -scheme Runner \
            -sdk iphonesimulator \
            CODE_SIGNING_ALLOWED=NO
