workflows:
  ios-simulator:
    name: iOS Simulator Build
    environment:
      xcode: latest
      flutter: stable
    
    scripts:
      - name: Flutter environment setup
        script: |
          echo "=== Flutter Version ==="
          flutter --version
          echo ""
          echo "=== Flutter Doctor ==="
          flutter doctor -v
          
      - name: Clean and prepare
        script: |
          flutter clean
          flutter pub get
          flutter pub upgrade
          
      - name: Build iOS simulator app
        script: |
          # Правильная команда сборки без устаревших флагов
          flutter build ios \
            --simulator \
            --no-codesign \
            --debug \
            --verbose
          
      - name: Verify and package build
        script: |
          if [ -d "build/ios/iphonesimulator/Runner.app" ]; then
            echo "✅ Build successful!"
            echo "App size:"
            du -sh build/ios/iphonesimulator/Runner.app
            
            # Упаковываем артефакты
            mkdir -p artifacts
            cp -R build/ios/iphonesimulator/Runner.app artifacts/
          else
            echo "❌ Build failed - app not found"
            echo "Searching for build artifacts:"
            find . -name "*.app" -type d
            exit 1
          fi
    
    artifacts:
      - artifacts/Runner.app
