workflows:
  ios-simulator:
    name: iOS Simulator Build
    environment:
      xcode: latest
      flutter: stable
    
    scripts:
      - name: Setup Flutter environment
        script: |
          flutter doctor -v
          flutter --version
          
      - name: Clean and install dependencies
        script: |
          flutter clean
          flutter pub get
          flutter pub upgrade
          
      - name: Build for iOS simulator
        script: |
          flutter build ios --simulator --no-codesign --debug --verbose
          
      - name: Collect build artifacts
        script: |
          mkdir -p artifacts
          cp -R build/ios/iphonesimulator/Runner.app artifacts/
          echo "Build contents:"
          find artifacts/ -name "*.app" -type d
    
    artifacts:
      - artifacts/Runner.app
