workflows:
  ios-simulator:
    name: iOS Simulator Build
    environment:
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Check and generate workspace
        script: |
          echo "=== Checking iOS directory ==="
          ls -la ios/
          
          echo "=== Generating workspace ==="
          cd ios
          
          # Если workspace нет - создаем через pod install
          if [ ! -d "Runner.xcworkspace" ]; then
            echo "Workspace not found, generating..."
            pod install --repo-update --verbose
          fi
          
          # Проверяем что workspace создался
          if [ ! -d "Runner.xcworkspace" ]; then
            echo "❌ Still no workspace after pod install"
            echo "Trying alternative approach..."
            
            # Пробуем через xcodebuild
            xcodebuild -list
          fi
          
          cd ..
      
      - name: Build using project instead
        script: |
          cd ios
          
          # Используем .xcodeproj вместо .xcworkspace
          xcodebuild build \
            -project Runner.xcodeproj \
            -scheme Runner \
            -sdk iphonesimulator \
            -destination "generic/platform=iOS Simulator" \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES
