workflows:
  ios-debug:
    name: iOS Build
    environment:
      flutter: "3.32.0"
      xcode: "15.4"
    scripts:
      - name: Setup environment
        script: |
          echo "Flutter version:"
          flutter --version
          echo "Xcode version:"
          xcodebuild -version
          
      - name: Create Generated.xcconfig
        script: |
          mkdir -p ios/Flutter
          echo "FLUTTER_ROOT=/Users/builder/programs/flutter" > ios/Flutter/Generated.xcconfig
          echo "FLUTTER_APPLICATION_PATH=/Users/builder/clone" >> ios/Flutter/Generated.xcconfig
          echo "FLUTTER_TARGET=lib/main.dart" >> ios/Flutter/Generated.xcconfig
          echo "FLUTTER_BUILD_DIR=build" >> ios/Flutter/Generated.xcconfig
          echo "FLUTTER_BUILD_NAME=1.0.0" >> ios/Flutter/Generated.xcconfig
          echo "FLUTTER_BUILD_NUMBER=1" >> ios/Flutter/Generated.xcconfig
          echo "APPLICATION_PATH=." >> ios/Flutter/Generated.xcconfig
          echo "Generated.xcconfig content:"
          cat ios/Flutter/Generated.xcconfig

      - name: Get dependencies
        script: |
          flutter pub get

      - name: Install pods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build with detailed logging
        script: |
          flutter clean
          flutter build ios --simulator --no-codesign --verbose

      - name: Verify build
        script: |
          if [ -d "build/ios/iphonesimulator/Runner.app" ]; then
            echo "✅ Build successful!"
          else
            echo "❌ Build failed"
            exit 1
          fi

    artifacts:
      - build/ios/iphonesimulator/**/*.app
