workflows:
  ios-debug:
    name: iOS Build without Firebase
    environment:
      flutter: "3.32.0"
    scripts:
      - name: Setup
        script: |
          mkdir -p ios/Flutter
          echo "FLUTTER_ROOT=/Users/builder/programs/flutter" > ios/Flutter/Generated.xcconfig
          echo "FLUTTER_APPLICATION_PATH=/Users/builder/clone" >> ios/Flutter/Generated.xcconfig
          echo "FLUTTER_TARGET=lib/main.dart" >> ios/Flutter/Generated.xcconfig

      - name: Modify Podfile to exclude Firebase for simulator
        script: |
          cd ios
          # Создаем backup
          cp Podfile Podfile.backup
          # Комментируем Firebase pods для симулятора
          sed -i '' 's/^.*Firebase.*$/# &/' Podfile
          pod install --repo-update
          cd ..

      - name: Build without Firebase
        script: |
          flutter build ios --simulator --no-codesign

      - name: Restore Podfile
        script: |
          cd ios
          mv Podfile.backup Podfile
          cd ..
