workflows:
  ios-simulator:
    name: iOS Simulator Build
    environment:
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Clean and reinstall pods
        script: |
          cd ios
          # Полная очистка
          rm -rf Pods Podfile.lock Runner.xcworkspace
          pod cache clean --all
          pod deintegrate
          
          # Переустановка
          pod install --repo-update --verbose
          cd ..
      
      - name: Build with fixed pod paths
        script: |
          cd ios
          # Сборка с явным указанием путей
          xcodebuild build \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -sdk iphonesimulator \
            -destination "generic/platform=iOS Simulator" \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES \
            DERIVED_DATA_PATH="./build" \
            -quiet
