workflows:
  ios-debug:
    name: iOS Debug Build
    environment:
      xcode: latest
      flutter: stable
    
    scripts:
      - name: Build with disabled firebase scripts
        script: |
          flutter clean
          flutter pub get
          
          # Временно отключаем скрипты Firebase
          cd ios
          if [ -f "Podfile" ]; then
            # Комментируем проблемные скрипты
            sed -i '' 's/^ *flutterfire/# flutterfire/g' Podfile 2>/dev/null || true
          fi
          cd ..
          
          flutter build ios --simulator --no-codesign --verbose 2>&1 | tee error_log.txt
          
          mkdir -p error_logs
          cp error_log.txt error_logs/
          
          # Проверяем успешность сборки
          if [ -d "build/ios/iphonesimulator/Runner.app" ]; then
            echo "✅ Build successful!"
            exit 0  # Успешный выход
          else
            echo "❌ Build failed"
            exit 1  # Выход с ошибкой
          fi
    
    artifacts:
      - error_logs/error_log.txt
      - build/ios/iphonesimulator/Runner.app
