workflows:
  ios-simulator:
    name: iOS Simulator Build
    environment:
      xcode: latest
      flutter: stable
    
    scripts:
      - name: Recreate iOS project
        script: |
          # Сохраняем важные файлы
          if [ -f "ios/Runner/Info.plist" ]; then
            cp ios/Runner/Info.plist Info.plist.backup
          fi
          if [ -f "ios/Runner/Assets.xcassets" ]; then
            cp -R ios/Runner/Assets.xcassets Assets.backup
          fi
          
          # Полная перегенерация
          flutter clean
          rm -rf ios
          flutter create --platforms=ios --project-name Runner .
          
          # Восстанавливаем файлы
          if [ -f "Info.plist.backup" ]; then
            cp Info.plist.backup ios/Runner/Info.plist
          fi
          if [ -d "Assets.backup" ]; then
            cp -R Assets.backup/* ios/Runner/Assets.xcassets/
          fi
          
          flutter pub get
      
      - name: Build fresh project
        script: |
          flutter build ios --simulator --no-codesign --debug
