workflows:
  ios-debug:
    name: iOS Debug Build
    environment:
      xcode: latest
      flutter: stable
      cocoapods: default
    
    scripts:
      - name: Clean and setup
        script: |
          echo "=== Cleaning ==="
          rm -rf /tmp/flutter_*
          rm -rf /var/folders/*/T/flutter_tools.*
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/Runner.xcworkspace
          flutter pub get
          
      - name: Install pods
        script: |
          cd ios
          pod install --repo-update --verbose
          cd ..
          
      - name: Build iOS
        script: |
          set -e
          mkdir -p logs
          
          # Пытаемся собрать
          if flutter build ios --simulator --no-codesign --verbose 2>&1 | tee logs/build.log; then
            echo "✅ Build successful!"
          else
            echo "❌ Build failed"
            exit 1
          fi
        
    artifacts:
      - /Users/builder/Library/Developer/Xcode/DerivedData/**/*.app
