name: rider_flutter
description: Ride-sharing
publish_to: "none"

version: 3.2.8+278

environment:
  sdk: ^3.6.0
  flutter: ^3.27.0

dependencies:
  sentry_flutter: ^8.14.1
  flutter:
    sdk: flutter

  freezed_annotation: ^2.4.4

  # Geo
  latlong2: ^0.9.1
  geolocator: ^13.0.2

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # State management
  flutter_bloc: ^8.1.5
  hydrated_bloc: ^9.1.5

  # Dependency injection
  get_it: ^8.0.2
  injectable: ^2.4.1

  # Routing
  auto_route: ^9.2.2

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.1.0

  # Helpers
  dartz: ^0.10.1
  rxdart: ^0.28.0
  equatable: ^2.0.3
  path_provider: ^2.1.2
  json_annotation: ^4.9.0
  url_launcher: ^6.2.5
  connectivity_plus: ^6.0.3

  # Firebase
  #firebase_analytics: ^11.3.6
  firebase_core: ^2.32.0        # Оставьте 2.x
  firebase_messaging: ^14.7.10  # Понизьте до 14.x
  #firebase_crashlytics: ^4.2.0


  # UI
  ionicons: 0.2.2
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.64.0
  dotted_border: ^2.1.0
  generic_map:
    path: libs/generic_map
  flutter_common:
    path: libs/flutter_common
  lottie: ^3.1.0

  # Network
  graphql: ^5.2.0-beta.7
  cached_network_image: ^3.3.1
  collection: ^1.17.2
  dotted_line: ^3.2.2
  share_plus: ^10.1.2
  package_info_plus: ^8.1.1

dev_dependencies:
  sentry_dart_plugin: ^2.4.1
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  flutter_gen_runner: ^5.4.0
  flutter_gen: ^5.4.0
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.1
  build_verify: ^3.1.0
  graphql_codegen: ^1.1.1
  freezed: ^2.5.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4


flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/avatars/
    - assets/lottie/
    - assets/countries/

  fonts:
    - family: GeneralSans
      fonts:
        - asset: assets/fonts/generalsansextralight.ttf
          weight: 200
        - asset: assets/fonts/generalsanslight.ttf
          weight: 300
        - asset: assets/fonts/generalsansregular.ttf
          weight: 400
        - asset: assets/fonts/generalsansmedium.ttf
          weight: 500
        - asset: assets/fonts/generalsanssemibold.ttf
          weight: 600
        - asset: assets/fonts/generalsansbold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/interthin.ttf
          weight: 100
        - asset: assets/fonts/interextralight.ttf
          weight: 200
        - asset: assets/fonts/interlight.ttf
          weight: 300
        - asset: assets/fonts/interregular.ttf
          weight: 400
        - asset: assets/fonts/intermedium.ttf
          weight: 500
        - asset: assets/fonts/intersemibold.ttf
          weight: 600
        - asset: assets/fonts/interbold.ttf
          weight: 700
        - asset: assets/fonts/interextrabold.ttf
          weight: 800
        - asset: assets/fonts/interblack.ttf
          weight: 900

flutter_gen:
  integrations:
    lottie: true

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: taxi-rider
  org: lumeagency
