// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCovBrjb3r31qsjSdrQfLa-hzX_Huwe2qw',
    appId: '1:912880218902:web:159eab3afdc05f92339637',
    messagingSenderId: '912880218902',
    projectId: 'newagent-2302f',
    authDomain: 'newagent-2302f.firebaseapp.com',
    databaseURL: 'https://newagent-2302f.firebaseio.com',
    storageBucket: 'newagent-2302f.appspot.com',
    measurementId: 'G-T90K1QQLJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0N5OoDrfxjk4ynqw3rNswKTKaZEze6Mg',
    appId: '1:912880218902:android:5cecbee9b0475b08339637',
    messagingSenderId: '912880218902',
    projectId: 'newagent-2302f',
    databaseURL: 'https://newagent-2302f.firebaseio.com',
    storageBucket: 'newagent-2302f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxeoSyXiDOrQdmBuQPDxgbm4iYTHwhIw4',
    appId: '1:912880218902:ios:91399a646b5525df339637',
    messagingSenderId: '912880218902',
    projectId: 'newagent-2302f',
    databaseURL: 'https://newagent-2302f.firebaseio.com',
    storageBucket: 'newagent-2302f.appspot.com',
    androidClientId: '912880218902-0b6s18qvning41jdhmfhevic424o4r48.apps.googleusercontent.com',
    iosClientId: '912880218902-9sjen2eruik9n108sdjuhtiugcc7g1a0.apps.googleusercontent.com',
    iosBundleId: 'com.ridy.taxi.rider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxeoSyXiDOrQdmBuQPDxgbm4iYTHwhIw4',
    appId: '1:912880218902:ios:c7a715e61c35a905339637',
    messagingSenderId: '912880218902',
    projectId: 'newagent-2302f',
    databaseURL: 'https://newagent-2302f.firebaseio.com',
    storageBucket: 'newagent-2302f.appspot.com',
    androidClientId: '912880218902-0b6s18qvning41jdhmfhevic424o4r48.apps.googleusercontent.com',
    iosBundleId: 'com.gotaxi.taxi.riderFlutter',
  );

}